### ISSUE TITLE
Support name-based hosts via TLS SNI

### ISSUE THREAD

**Issue by Castaglia** [Castaglia/proftpd-mod_autohost#5]
Some sites may wish to host large numbers of vhosts on the same IP address.  One way that `mod_autohost` could handle these, in addition to (or related to) [`HOST`] (see Issue #1) could be to look up the vhost config based on TLS SNI.

Given that the TLS handshake for FTPS connections happens sometime _after_ the initial TCP connection, where any number of commands might happen, supporting SNI will not be as straightforward as destination IP-based lookups.  There might be an "initial" config for use such connections, until such time as they provide an SNI via TLS handshake (and/or `HOST` command).

**Comment by jrhay1** [comment]
Any thoughts on when this might be available?

**Comment by e-fik123** [comment]
Any progress here? Would be great to have a sni support for PROFTPD

**Comment by FGasper** [comment]
@Castaglia NB: Pure-FTPd just implemented SNI support. Maybe the implementation there would be a useful blueprint?

**Comment by Castaglia** [comment]
@e-fik123 ProFTPD's `mod_tls` _does_ support SNI.  This particular feature request is specifically for the mass vhosting capabilities of `mod_autohost`, to use the SNI, if provided, to select the appropriate configuration.  I'm looking into this now.

**Comment by FGasper** [comment]
Where is the current SNI support documented?

**Comment by e-fik123** [comment]
@Castaglia i read the docu for `mod_autohost` but there is reference only to IP addresses, missing hostnames. If you got any progress or need help, let me know.
as @FGasper mentioned pure-ftpd uses extra deamon for sni support maybe this can be a way to do this.
Pure-ftpd does not support proxying so no alternative for me

**Comment by FGasper** [comment]
If possible, perhaps even use the _same_ SNI daemon that Pure-FTPd uses. There’s no reason to reinvent the wheel, after all.

**Comment by e-fik123** [comment]
Any update here? to me this is still important topic. If you need any help let me know.

**Comment by Castaglia** [comment]
Notes for myself, for SNI-related configurations:
* When can we do the lookup for a config, using SNI?  _Answer_: in a `LOG_CMD` handler for the `AUTH TLS` command; that is when we _know_ that a TLS handshake occurred.
* What happens if no SNI is provided?  Nothing different than normal.
* What happens if no matching config for the given SNI is available?  Nothing different than normal.
* What about connection-time limits/ACLs in the new config?  They will be ignored.

**Comment by Castaglia** [comment]
@FGasper @e-fik123 @jrhay1 FYI, this ticket is about supporting SNI as part of the lookup syntax for these dynamically loaded config files.  For SNI support in `mod_tls`, see https://github.com/proftpd/proftpd/issues/850.

**Comment by FGasper** [comment]
@Castaglia: Just so I’m clear, does the current feature set allow ProFTPd to allow the SNI string to determine which of a set of certificates (either pre-loaded or runtime-determined) is served up?

**Comment by Castaglia** [comment]
@FGasper @e-fik123 Now that SNI support in `mod_tls` is stabilizing; see:
* https://github.com/proftpd/proftpd/issues/850
* https://github.com/proftpd/proftpd/issues/924
* https://github.com/proftpd/proftpd/issues/932

I can now start properly working on SNI support for `mod_autohost`.

**Comment by Castaglia** [comment]
Fixed in `master`.
